### ISSUE TITLE
devstack.py config migration for all IDAs

### ISSUE THREAD

**Issue by UsamaSadiq** [edx/devstack#68]
## Description
- Under the discovery done on the [DEPR notice](https://github.com/openedx/public-engineering/issues/247) issued by AXIM, it was decided to move the config files completely into the devstack repository and mount the required volumes with the devstack container. 

## AC
- Similar to the approach implemented and tested for credentials service in PRs https://github.com/edx/devstack/pull/57 and https://github.com/edx/devstack/pull/64, apply the similar changes to the remaining IDAs as well.

```[tasklist]
### Tasks
- [x] registrar
- [x] Credentials
- [x] Course-Discovery
- [x] edx-platform
- [x] enterprise-access
- [x] enterprise-subsidy
- [x] edx-notes-api
- [x] enterprise-catalog
- [x] xqueue
- [x] analytics-data-api
- [x] analytics-dashboard
- [x] ecommerce
- [x] commerce-coordinator
- [x] edx-exams
- [x] program-intent-engagement
- [x] portal-designer
- [x] license-manager
```

**Comment by iamsobanjaved** [comment]
Devstack PR: 
- https://github.com/edx/devstack/pull/72
