### ISSUE TITLE
Add openedx/enterprise-access to devstack

### ISSUE THREAD

**Issue by iamsobanjaved** [edx/devstack#75]
Under https://github.com/edx/devstack/issues/80, we need to add openedx/license-manager to devstack. Follow the tasklist and also add this tasklist on the PR as a reviewer checklist.

**Repo:** https://github.com/openedx/enterprise-access

```[tasklist]
### Tasks
- [x] Add the service in `docker-compose.yml` file, follow `docker-compose.yml` file from the source repo.
- [ ] Add `dev.shell` make command if some extra env variables need to be set
- [ ] Add an entry in `check.sh` if needed
- [x] Mount volume in `docker-compose-host.yml` file
- [ ] Add entry in `options.mk` file
- [ ] Create `provision-IDA_NAME.sh` file if needed. Also, add an entry in `provision.sh` file.
- [ ] Create table in `provision.sql` file if needed
- [ ] Add an entry in `repo.sh` file.
- [ ] Add an entry in `service_list.rst` file.
```
